[Fix]: In res_users, create context_lang at start.
This fixes creating a new db.

res_users is created in static SQL, because it must exist
before anything else. There, context_lang must exist as well.
Additionaly, init res_lang before res_users.

Trace:
   File "./bin/osv/orm.py", line 1560, in _auto_init
     default = self._defaults[k](self, cr, 1, {})
   File "./bin/addons/base/res/res_user.py", line 152, in _get_company
     return self.pool.get('res.users').browse(cr, uid, uid,
context).company_id.id
   File "./bin/osv/orm.py", line 225, in __getattr__
     return self[name]
   File "./bin/osv/orm.py", line 182, in __getitem__
     datas = self._table.read(self._cr, self._uid, ids, fffields,
context=self._context, load="_classic_write")
   File "./bin/addons/base/res/res_user.py", line 127, in read
     result = super(users, self).read(cr, uid, ids, fields, context,
load)
   File "./bin/osv/orm.py", line 1905, in read
     result = self._read_flat(cr, user, select, fields, context, load)
   File "./bin/osv/orm.py", line 1959, in _read_flat
     self._order))
   File "./bin/sql_db.py", line 78, in wrapper
     return f(self, *args, **kwargs)
   File "./bin/sql_db.py", line 120, in execute
     res = self._obj.execute(query, params)
 ProgrammingError: column "context_lang" does not exist
 LINE 1:
...text_tz","name","company_id","signature","active","context_l...

bzr revid: p_christ@hol.gr-20090312083416-r7yjmipqik0k0kd1