yaml_import: fix ambiguous syntax at end of report
When finishing a YAML import, the syntax ["str %d" % int + int] turns
out to be ambiguous and is resolved as [ ("str %d" % int) + int],
leading to a:
  TypeError: cannot concatenate 'str' and 'int' objects

This had been first fixed in commit f46966e044d18a644 (2010-06-30)
(cherry picked from commit cc0c584e5dfbf672d51f61e7207047f357e31471)

bzr revid: xrg@linux.gr-20110605135116-ie2h7gnvnx2kpdoy